name: CI

on:
  push:
  pull_request:

jobs:
  phpstan:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: [8.1, 8.2, 8.3, 8.4]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: composer

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist --ignore-platform-req=*

      - name: Run PHPStan
        run: composer phpstan
